# _config.yml

title: "EGGS-Studio"
description: "Arte y vida"
theme: minima

# Configuraci칩n de Kramdown para procesar Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

# Configuraci칩n de Mermaid.js
mermaid:
  version: "9.3.0" # Especifica la versi칩n de Mermaid.js que est치s utilizando
