title: "EGGS-Studio"
description: "Arte y vida: murales, restauración y diseño artístico."
theme: minima

# URL de tu sitio
url: "https://eggs-studio.cl"
baseurl: ""  # Dejar vacío si no usas subcarpeta

# Palabras clave y autor
keywords: "arte visual, murales, restauración de arte, diseño artístico, talleres artísticos, EGGS-Studio, Esteban Garnica"
author: "Esteban Garnica"

# Plugins de Jekyll
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-multiple-languages (Si decides usar internacionalización avanzada)

# Configuración de Markdown
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true
    wrap: true

# Configuración para Mermaid.js
mermaid:
  version: "10.0.0"
  options:
    theme: "forest"
    flowchart:
      curve: "basis"

# Exclusión de archivos innecesarios
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Idiomas disponibles
languages:
  es:
    label: "Español"
    locale: "es-ES"
    dir: "ltr"
  en:
    label: "English"
    locale: "en-US"
    dir: "ltr"

# Configuración por defecto para cada idioma
defaults:
  - scope:
      path: "ES"
    values:
      lang: "es"
      locale: "es-ES"
  - scope:
      path: "EN"
    values:
      lang: "en"
      locale: "en-US"

# Configurar enlaces permanentes más legibles
permalink: pretty

# Colecciones de productos (Impresiones, etc.)
collections:
  productos_es:
    output: true
    permalink: /es/productos/:path/
  productos_en:
    output: true
    permalink: /en/products/:path/
