# _config.yml

# Información del sitio
title: "EGGS-Studio"
description: "Arte y vida"
theme: minima

# Configuración de Markdown con Kramdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3

# Configuración para integrar Mermaid.js
mermaid: true

mermaid:
  src: "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"
