# _config.yml

title: "EGGS-Studio"
description: "Arte y vida"
theme: minima

# Configuración de Kramdown para procesar Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

# Configuración de Mermaid.js
mermaid:
  version: "10.9.3" # Especifica la nueva versión de Mermaid.js
