title: "EGGS-Studio"
description: "Arte y vida: murales, restauración y diseño artístico."
theme: minima
url: "https://eggs-studio.cl"
baseurl: "" # No agregar prefijo a las URLs

# Palabras clave y autor
keywords: "arte visual, murales, restauración de arte, diseño artístico, talleres artísticos, EGGS-Studio, Esteban Garnica"
author: "Esteban Garnica"

# Sitemap y plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de Markdown
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true
    wrap: true

# Configuración de Mermaid.js
mermaid:
  version: "9.3.0"
  options:
    theme: "forest"
    flowchart:
      curve: "basis"

# Exclusión de archivos innecesarios
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Idiomas
languages:
  es:
    label: "Español"
    locale: "es-ES"
    dir: "ltr"
  en:
    label: "English"
    locale: "en-US"
    dir: "ltr"

# Configuración predeterminada para los idiomas
defaults:
  - scope:
      path: "es"
    values:
      lang: "es"
      locale: "es-ES"
  - scope:
      path: "en"
    values:
      lang: "en"
      locale: "en-US"

