// Productos estandarizados generados desde _productos_es. No editar manualmente.
const DELIVERY_OPTIONS = Object.freeze({
  santiago: "Entrega sin costo en Santiago",
  quote_later: "Despacho fuera de Santiago cotizado y pagado después",
});

const PRODUCTS = Object.freeze({
  "EGGS-S0002-L01-P4050-F5070": Object.freeze({
    title: "Infected Paintings 1–4",
    description: "Conjunto de impresiones de 2008. 20 conjuntos + 2 pruebas de artista. Disponible por producir.",
    currency: "CLP",
    unitPrice: 800000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-S0003-L01-P5070-F70100": Object.freeze({
    title: "Paisajes de Carretera 01–06",
    description: "Conjunto de impresiones de 2008. 20 conjuntos + 2 pruebas de artista. Disponible por producir.",
    currency: "CLP",
    unitPrice: 1350000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-S0004-L01-P6060-F8080": Object.freeze({
    title: "Díptico Autofusión",
    description: "Conjunto de impresiones de 2008. 20 dípticos + 2 pruebas de artista. Disponible por producir.",
    currency: "CLP",
    unitPrice: 520000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-S0005-L01-P5070-F70100": Object.freeze({
    title: "Banderas infectadas n.º 1–2",
    description: "Conjunto de impresiones de 2010. 20 conjuntos + 2 pruebas de artista. Disponible por producir.",
    currency: "CLP",
    unitPrice: 470000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-S0006-L01-P70120-F80130": Object.freeze({
    title: "Díptico conceptual Gran Paisaje 01–02",
    description: "Conjunto de impresiones de 2010. 10 dípticos + 2 pruebas de artista. Disponible por producir.",
    currency: "CLP",
    unitPrice: 900000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-S0008-PUB01": Object.freeze({
    title: "Intervenciones publicitarias 2007–2011",
    description: "Publicación de artista de 2007. 50 ejemplares + 5 pruebas de artista. Disponible por producir.",
    currency: "CLP",
    unitPrice: 120000,
    initialStock: 50,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-S0009-PUB01-LEP": Object.freeze({
    title: "Remiendas Urbanas",
    description: "Publicación de artista en leporello y edición numerada, actualmente por producir.",
    currency: "CLP",
    unitPrice: 95000,
    initialStock: 50,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0001-L01-P5070-F70100": Object.freeze({
    title: "Caleta Infectada",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0002-L01-P5070-F70100": Object.freeze({
    title: "ARTE",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0003-L01-P4050-F5070": Object.freeze({
    title: "Infected Paintings 1",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible.",
    currency: "CLP",
    unitPrice: 220000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0004-L01-P4050-F5070": Object.freeze({
    title: "Infected Paintings 2",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible.",
    currency: "CLP",
    unitPrice: 220000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0005-L01-P4050-F5070": Object.freeze({
    title: "Infected Paintings 3",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible.",
    currency: "CLP",
    unitPrice: 220000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0006-L01-P4050-F5070": Object.freeze({
    title: "Infected Paintings 4",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible.",
    currency: "CLP",
    unitPrice: 220000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0007-L01-P5070-F70100": Object.freeze({
    title: "Pintura infectada Mujer en Bici",
    description: "Edición limitada de 2010. 20 ejemplares + 2 pruebas de artista. Disponible como print; original no disponible.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0008-L01-P5070-F70100": Object.freeze({
    title: "Paisaje de Carretera 01",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0009-L01-P5070-F70100": Object.freeze({
    title: "Paisaje de Carretera 02",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0010-L01-P5070-F70100": Object.freeze({
    title: "Paisaje de Carretera 03",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0011-L01-P5070-F70100": Object.freeze({
    title: "Paisaje de Carretera 04",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0012-L01-P5070-F70100": Object.freeze({
    title: "Paisaje de Carretera 05",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0013-L01-P5070-F70100": Object.freeze({
    title: "Paisaje de Carretera 06",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0016-L01-P5070-F70100": Object.freeze({
    title: "Bandera infectada n.º 1",
    description: "Edición limitada de 2010. 20 ejemplares + 2 pruebas de artista. Disponible como print; original de paradero desconocido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0017-L01-P5070-F70100": Object.freeze({
    title: "Bandera infectada n.º 2",
    description: "Edición limitada de 2011. 20 ejemplares + 2 pruebas de artista. Disponible como print; original perdido / paradero desconocido.",
    currency: "CLP",
    unitPrice: 260000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0018-L01-P6060-F8080": Object.freeze({
    title: "Membrana sin título n.º 1 / Verde",
    description: "Edición limitada de 2008. 20 ejemplares + 2 pruebas de artista. Disponible, sujeto a revisión de conservación.",
    currency: "CLP",
    unitPrice: 290000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0019-PUB01-LEP": Object.freeze({
    title: "Mapamundi",
    description: "Publicación de artista en edición numerada, actualmente por producir.",
    currency: "CLP",
    unitPrice: 85000,
    initialStock: 50,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0020-L01-P6060-F8080": Object.freeze({
    title: "Dos Hombres Selknam",
    description: "Edición limitada de 2013. 20 ejemplares + 2 pruebas de artista. Disponible únicamente como print; original existente pero inaccesible para el artista.",
    currency: "CLP",
    unitPrice: 290000,
    initialStock: 20,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0021-L01-P90120-F110140": Object.freeze({
    title: "Paisaje Urbano",
    description: "Edición limitada de 2010. 15 ejemplares + 2 pruebas de artista. Disponible; obra en buen estado para vender.",
    currency: "CLP",
    unitPrice: 520000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0022-L01-P70100-F80110": Object.freeze({
    title: "Cordillera",
    description: "Edición fotográfica documental de 2009, numerada y certificada.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0023-L01-P70120-F80130": Object.freeze({
    title: "Pintura infectada: Gran Paisaje 01 / Gran Paisaje Saturado n.º 1",
    description: "Edición limitada de 2010. 10 ejemplares + 2 pruebas de artista. Disponible; obra firmada y en buen estado.",
    currency: "CLP",
    unitPrice: 480000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0024-L01-P70120-F80130": Object.freeze({
    title: "Gran Paisaje 02 / Gran Paisaje Saturado n.º 2",
    description: "Edición limitada de 2012. 10 ejemplares + 2 pruebas de artista. Disponible; obra firmada y en buen estado.",
    currency: "CLP",
    unitPrice: 480000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0033-L01-P60110-F70120": Object.freeze({
    title: "Árbol",
    description: "Edición fotográfica documental de 2009, numerada y certificada.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0034-L01-P70100-F80110": Object.freeze({
    title: "Automóvil",
    description: "Edición limitada de 2009. 10 ejemplares + 2 pruebas de artista. Disponible como edición fotográfica por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0035-L01-P5070-F70100": Object.freeze({
    title: "Baño / objeto de pandemia",
    description: "Edición limitada de 2020. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 360000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0038-L01-P70100-F80110": Object.freeze({
    title: "Avalancha",
    description: "Edición fotográfica documental de 2009, numerada y certificada.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0039-L01-P70100-F80110": Object.freeze({
    title: "Peste Doméstica n1",
    description: "Edición limitada de 2008. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0040-L01-P5070-F70100": Object.freeze({
    title: "Peste Doméstica n2",
    description: "Edición limitada de 2008. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 360000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0041-L01-P70100-F80110": Object.freeze({
    title: "Cocina Cubierta",
    description: "Edición limitada de 2008. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0044-L01-P5070-F70100": Object.freeze({
    title: "Busto de O’Higgins",
    description: "Edición limitada de 2011. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 360000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0045-L01-P70100-F80110": Object.freeze({
    title: "Ruralias",
    description: "Edición limitada de 2012. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0046-L01-P70100-F80110": Object.freeze({
    title: "Paisaje Wi-fi n1",
    description: "Edición limitada de una pintura de 2016, numerada y certificada.",
    currency: "CLP",
    unitPrice: 420000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0047-L01-P70100-F80110": Object.freeze({
    title: "Paisaje Wi-fi n2",
    description: "Edición limitada de 2016. 15 ejemplares + 2 pruebas de artista. Disponible únicamente como edición limitada por producir.",
    currency: "CLP",
    unitPrice: 420000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0048-L01-P70100-F80110": Object.freeze({
    title: "Paisaje Wi-fi n3",
    description: "Edición limitada de 2020. 15 ejemplares + 2 pruebas de artista. Disponible únicamente como edición limitada por producir.",
    currency: "CLP",
    unitPrice: 420000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0049-L01-P70100-F80110": Object.freeze({
    title: "Paisaje Wi-fi n4",
    description: "Edición limitada de 2020. 15 ejemplares + 2 pruebas de artista. Disponible únicamente como edición limitada por producir.",
    currency: "CLP",
    unitPrice: 420000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0050-L01-P70100-F80110": Object.freeze({
    title: "Retrato Wi-fi n1",
    description: "Edición limitada de 2020. 15 ejemplares + 2 pruebas de artista. Disponible únicamente como edición limitada por producir.",
    currency: "CLP",
    unitPrice: 420000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0051-L01-P70100-F80110": Object.freeze({
    title: "Bodegón Wi-fi n1",
    description: "Edición limitada de 2018. 15 ejemplares + 2 pruebas de artista. Disponible únicamente como edición limitada por producir.",
    currency: "CLP",
    unitPrice: 420000,
    initialStock: 15,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0052-L01-P5070-F70100": Object.freeze({
    title: "Papelucho",
    description: "Edición limitada de 2022. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 360000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0053-L01-P110160-F120170": Object.freeze({
    title: "El Colgado N.º 01",
    description: "Fotografía de autor de 2010 en edición limitada, numerada y certificada.",
    currency: "CLP",
    unitPrice: 950000,
    initialStock: 5,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0054-L01-P110160-F120170": Object.freeze({
    title: "El Colgado N.º 02",
    description: "Edición fotográfica de 2008. 5 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 950000,
    initialStock: 5,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0055-L01-P110160-F120170": Object.freeze({
    title: "El Colgado N.º 03",
    description: "Edición fotográfica de 2009. 5 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 950000,
    initialStock: 5,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0056-L01-P110160-F120170": Object.freeze({
    title: "El Colgado N.º 04",
    description: "Edición fotográfica de 2010. 5 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 950000,
    initialStock: 5,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0057-L01-P110160-F120170": Object.freeze({
    title: "El Colgado N.º 05",
    description: "Edición fotográfica de 2012. 5 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 950000,
    initialStock: 5,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0074-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Mapuche — Hombre",
    description: "Edición limitada de 2018. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0075-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Mapuche — Mujer",
    description: "Edición limitada de 2018. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0076-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Aimara — Hombre",
    description: "Edición limitada de 2019. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0077-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Aimara — Mujer",
    description: "Edición limitada de 2019. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0078-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Rapa Nui — Mujer",
    description: "Edición limitada de 2021. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0079-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Rapa Nui — Hombre",
    description: "Edición limitada de 2021. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0080-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Selknam — Mujer",
    description: "Edición limitada de 2021. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0081-L01-P70100-F80110": Object.freeze({
    title: "Pueblo Selknam — Hombre",
    description: "Edición limitada de 2021. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0127-L01-P70100-F80110": Object.freeze({
    title: "A villa A. Larraguibel y su memoria",
    description: "Edición fotográfica documental del mural realizado en 2024, numerada y certificada.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0128-L01-P70100-F80110": Object.freeze({
    title: "Día de la Madre",
    description: "Edición limitada de 2020. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0129-L01-P70100-F80110": Object.freeze({
    title: "Día del Padre",
    description: "Edición limitada de 2025. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0130-L01-P70100-F80110": Object.freeze({
    title: "Fuerza y Templanza de las Mascotas",
    description: "Edición limitada de 2025. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0132-L01-P70100-F80110": Object.freeze({
    title: "La Bendición de los Quillayes",
    description: "Edición limitada de 2023. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
  "EGGS-W0133-L01-P70100-F80110": Object.freeze({
    title: "Salmo 91:4",
    description: "Edición limitada de 2023. 10 ejemplares + 2 pruebas de artista. Disponible como edición por producir.",
    currency: "CLP",
    unitPrice: 450000,
    initialStock: 10,
    binaryMode: false,
    deliveryOptions: DELIVERY_OPTIONS,
  }),
});

module.exports = { PRODUCTS };
