#!/usr/bin/env python3
"""Generate Netlify redirects toward lowercase canonical language URLs."""

from __future__ import annotations

import argparse
from pathlib import Path


LANGUAGES = ("es", "en", "mpd", "chn")


def canonical_for(relative: Path) -> str:
    language = relative.parts[0]
    if relative == Path(language, "index.html"):
        return f"/{language}/index.html"
    if relative.name == "index.html":
        return "/" + relative.parent.as_posix().rstrip("/") + "/"
    return "/" + relative.as_posix()


def variants_for(relative: Path, canonical: str) -> set[str]:
    language = relative.parts[0]
    uppercase = language.upper()
    suffix = canonical[len(language) + 1 :]
    variants = {f"/{uppercase}{suffix}"}

    if relative == Path(language, "index.html"):
        variants.update(
            {
                f"/{language}",
                f"/{language}/",
                f"/{language}/index",
                f"/{language}/index/",
                f"/{uppercase}",
                f"/{uppercase}/",
                f"/{uppercase}/index",
                f"/{uppercase}/index/",
                f"/{uppercase}/index.html",
            }
        )
    elif canonical.endswith(".html"):
        extensionless = canonical[:-5]
        uppercase_extensionless = extensionless.replace(
            f"/{language}/", f"/{uppercase}/", 1
        )
        variants.update(
            {
                extensionless,
                extensionless + "/",
                uppercase_extensionless,
                uppercase_extensionless + "/",
                canonical.replace(f"/{language}/", f"/{uppercase}/", 1),
            }
        )
    elif relative.name == "index.html":
        uppercase_canonical = canonical.replace(
            f"/{language}/", f"/{uppercase}/", 1
        )
        variants.update(
            {
                uppercase_canonical,
                uppercase_canonical.rstrip("/"),
            }
        )

    variants.discard(canonical)
    return variants


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--site", type=Path, default=Path("_site"))
    args = parser.parse_args()
    site = args.site.resolve()

    redirects: dict[str, str] = {}
    for page in sorted(site.rglob("*.html")):
        relative = page.relative_to(site)
        if not relative.parts or relative.parts[0] not in LANGUAGES:
            continue
        canonical = canonical_for(relative)
        for source in variants_for(relative, canonical):
            if source.rstrip("/") == canonical.rstrip("/"):
                raise RuntimeError(
                    "Redirección circular equivalente detectada: "
                    f"{source} -> {canonical}"
                )
            redirects[source] = canonical

    destination = site / "_redirects"
    lines = [
        "# Generated by tools/generate_redirects.py; lowercase language URLs are canonical."
    ]
    lines.extend(
        f"{source} {target} 301!" for source, target in sorted(redirects.items())
    )
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Redirecciones generadas: {len(redirects)} en {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
